# UNIT IDS

UNIT_WORKER = 1

# Foot
UNIT_FOOT_RIFLE = 2
UNIT_FOOT_SAW = 3
UNIT_FOOT_RPG = 4
UNIT_FOOT_FLAME = 5
UNIT_FOOT_SNIPER = 6
UNIT_FOOT_BOMBER = 7
UNIT_FOOT_SHOCK = 35
UNIT_FOOT_TECH = 8
UNIT_FOOT_MEDIC = 9
UNIT_FOOT_MECH = 28
UNIT_FOOT_DOG = 30
UNIT_FOOT_JAVELIN = 41
UNIT_FOOT_ZOMBIE_MELEE = 100
UNIT_FOOT_ZOMBIE_TORSO = 101
UNIT_FOOT_ZOMBIE_BOOMER = 102
UNIT_FOOT_ZOMBIE_BOSS = 103
UNIT_FOOT_ADV_MECH = 37
UNIT_FOOT_PLASMA_MECH = 47
UNIT_FOOT_GLADIATOR_MECH = 48
UNIT_FOOT_COR_MECH = 67
# Land
UNIT_VEHICLE_TANKDRONE = 10
UNIT_VEHICLE_BUGGY = 11
UNIT_VEHICLE_HUMVEE = 12
UNIT_VEHICLE_MAV = 13
UNIT_VEHICLE_TANK1 = 14
UNIT_VEHICLE_TANK2 = 15
UNIT_VEHICLE_SHOCK = 36
UNIT_VEHICLE_TANK3 = 16
UNIT_VEHICLE_LASERTANK = 17
UNIT_VEHICLE_ANTIAIR = 18
UNIT_VEHICLE_JAMMER = 19
UNIT_VEHICLE_ANTIMISSILE = 20
UNIT_VEHICLE_MEGATANK = 21
UNIT_VEHICLE_GAT = 29
UNIT_VEHICLE_HELLFIRE = 32
UNIT_VEHICLE_TANKBUSTER = 34
UNIT_VEHICLE_ADV_TANK = 39
UNIT_VEHICLE_DEMO_TRUCK = 40
UNIT_VEHICLE_FLAMEASSAULT = 46
UNIT_VEHICLE_RAILGUN = 55
UNIT_VEHICLE_BROOD_MOTHER = 57
UNIT_VEHICLE_CRUSADER = 60
UNIT_VEHICLE_HOVER_TANK = 68
# Air
UNIT_AIR_WINGDRONE = 22
UNIT_AIR_CHOPPERDRONE = 23
UNIT_AIR_CHOPPER1 = 24
UNIT_AIR_CHOPPER2 = 25
UNIT_AIR_PLANE1 = 26
UNIT_AIR_PLANE2 = 27
UNIT_AIR_HAWK = 31
UNIT_AIR_BOMBER = 33
UNIT_AIR_ADV_COPTER = 38
UNIT_AIR_HELLSTORM = 42
UNIT_AIR_VALKYRIE = 54
UNIT_AIR_HALCYON = 56
UNIT_AIR_FLYING_FORTRESS = 70
UNIT_AIR_FLYING_FORTRESS_DRONE = 71
UNIT_AIR_WARHAWK_DRONE = 72
UNIT_VEHICLE_VANQUISHER = 75
UNIT_VEHICLE_BFG = 80

unit_ids = {}
unit_ids['Rifleman']        = UNIT_FOOT_RIFLE
unit_ids['Heavy Gunner']    = UNIT_FOOT_SAW
unit_ids['Rocket Launcher'] = UNIT_FOOT_RPG
unit_ids['Flamethrower']  	= UNIT_FOOT_FLAME
unit_ids['Sniper']          = UNIT_FOOT_SNIPER
unit_ids['Tech']            = UNIT_FOOT_TECH
unit_ids['Medic']           = UNIT_FOOT_MEDIC
unit_ids['Hercules']        = UNIT_FOOT_MECH
unit_ids['Suicide Bomber']  = UNIT_FOOT_BOMBER
unit_ids['Attack Dog']  	= UNIT_FOOT_DOG
unit_ids['Jackrabbit']      = UNIT_VEHICLE_TANKDRONE
unit_ids['Rocket Buggy']	= UNIT_VEHICLE_BUGGY
unit_ids['Humvee']          = UNIT_VEHICLE_HUMVEE
unit_ids['Razorback']       = UNIT_VEHICLE_MAV
unit_ids['Rhino']	        = UNIT_VEHICLE_TANK1 
unit_ids['Paladin']         = UNIT_VEHICLE_TANK2 
unit_ids['Challenger']      = UNIT_VEHICLE_TANK3 
unit_ids['Laser Tank']      = UNIT_VEHICLE_LASERTANK 
unit_ids['AA Gun']          = UNIT_VEHICLE_ANTIAIR 
unit_ids['Jammer']          = UNIT_VEHICLE_JAMMER 
unit_ids['Interceptor']     = UNIT_VEHICLE_ANTIMISSILE 
unit_ids['Mega Tank']       = UNIT_VEHICLE_MEGATANK 
unit_ids['Gatling Truck']	= UNIT_VEHICLE_GAT
unit_ids['Wing Drones']     = UNIT_AIR_WINGDRONE
unit_ids['Thunderbolt']     = UNIT_AIR_PLANE1
unit_ids['Raptor']          = UNIT_AIR_PLANE2
#unit_ids['UH-60 Chopper']   = UNIT_AIR_CHOPPER2
unit_ids['Copter Drones']   = UNIT_AIR_CHOPPERDRONE
unit_ids['Cobra']           = UNIT_AIR_CHOPPER1
unit_ids['Elite Warhawk']   = UNIT_AIR_HAWK
unit_ids['Hellfire']        = UNIT_VEHICLE_HELLFIRE
unit_ids['Kondor']			= UNIT_AIR_BOMBER
unit_ids['Honey Badger']	= UNIT_VEHICLE_TANKBUSTER
unit_ids['Flak Tank']		= UNIT_VEHICLE_ANTIAIR
unit_ids['Shock Trooper']	= UNIT_FOOT_SHOCK
unit_ids['Shock Tank']		= UNIT_VEHICLE_SHOCK
unit_ids['Demo Truck']		= UNIT_VEHICLE_DEMO_TRUCK
unit_ids['Colossus']		= UNIT_FOOT_ADV_MECH
unit_ids['Havoc']			= UNIT_AIR_ADV_COPTER
unit_ids['Behemoth']  		= UNIT_VEHICLE_ADV_TANK
unit_ids['Hellstorm']		= UNIT_AIR_HELLSTORM
unit_ids['Stinger']			= UNIT_FOOT_JAVELIN
unit_ids['Flame Assault Vehicle']			= UNIT_VEHICLE_FLAMEASSAULT
unit_ids['Vanguard']		= UNIT_FOOT_PLASMA_MECH
unit_ids['Gladiator']		= UNIT_FOOT_GLADIATOR_MECH
unit_ids['Valkyrie']		= UNIT_AIR_VALKYRIE
unit_ids['Enforcer']		= UNIT_VEHICLE_RAILGUN
unit_ids['Halcyon']			= UNIT_AIR_HALCYON
unit_ids['Brood Mother']	= UNIT_VEHICLE_BROOD_MOTHER
unit_ids['Crusader']		= UNIT_VEHICLE_CRUSADER
unit_ids['Vanquisher']		= UNIT_VEHICLE_VANQUISHER
unit_ids['BFG']				= UNIT_VEHICLE_BFG

unit_ids['Zombie Melee']	= UNIT_FOOT_ZOMBIE_MELEE
unit_ids['Zombie Torso']	= UNIT_FOOT_ZOMBIE_TORSO
unit_ids['Zombie Boomer']	= UNIT_FOOT_ZOMBIE_BOOMER
unit_ids['Zombie Boss']		= UNIT_FOOT_ZOMBIE_BOSS
unit_ids['Corrosion Mech']  = UNIT_FOOT_COR_MECH
unit_ids['Hover Tank']      = UNIT_VEHICLE_HOVER_TANK
unit_ids['Titan']      = UNIT_AIR_FLYING_FORTRESS
unit_ids['Titan Drone']      = UNIT_AIR_FLYING_FORTRESS_DRONE
unit_ids['Warhawk Drone']      = UNIT_AIR_WARHAWK_DRONE

# BUILDING IDS

b_ids = {}
b_ids['Metal Factory'] = 1
b_ids['Oil Pump'] = 2
b_ids['Metal Storage'] = 3 
b_ids['Oil Storage'] = 4
b_ids['Mine Factory'] = 5
b_ids['Power Plant'] = 6
b_ids['War Room'] = 11
b_ids['Airfield'] = 13
b_ids['Command Center'] = 14
b_ids['Go-Go Bar'] = 19
b_ids['Missile Turret'] = 20
b_ids['Mortar Tower'] = 20
b_ids['Gun Turret'] = 21
b_ids['Bunker'] = 22
b_ids['Laser Cannon'] = 23
b_ids['Tesla Coil'] = 25
b_ids['Academy'] = 26
b_ids['Communication Tower'] = 28
b_ids['Barracks'] = 29
b_ids['War Factory'] = 30
b_ids['Tech Center'] = 31
b_ids['Long Range Strike Mortar 1'] = 33
b_ids['Long Range Strike Mortar 2'] = 33
b_ids['Long Range Strike EMP 1'] = 33
b_ids['Long Range Strike Howitzer 1'] = 33 
b_ids['Long Range Strike Biochem 1'] = 33
b_ids['Long Range Strike Howitzer 2'] = 33
b_ids['Long Range Strike EMP 2'] = 33
b_ids['Long Range Strike Cruise Missile 1'] = 33
b_ids['Long Range Strike Biochem 2'] = 33
b_ids['Long Range Strike Cruise Missile 2'] = 33

# TOWER IDS

tower_ids = {}
tower_ids['TOWER_MACHINE_GUN'] = 1
tower_ids['TOWER_MORTAR'] = 2
tower_ids['TOWER_HELLFIRE'] = 3
tower_ids['TOWER_FLAK'] = 4
tower_ids['TOWER_PLASMA'] = 5
tower_ids['TOWER_LASER'] = 6
tower_ids['TOWER_ROCKET_BARRAGE'] = 7
tower_ids['TOWER_SHOCK'] = 8
tower_ids['TOWER_NAPALM'] = 9
tower_ids['TOWER_CRYO'] = 10
tower_ids['TOWER_BLITZ'] = 11
tower_ids['TOWER_BLITZ_PLATFORM'] = 12
tower_ids['TOWER_RS_SAM'] = 13
tower_ids['TOWER_ROCKET_ANTI_UNIQUE'] = 14
tower_ids['TOWER_ROCKET_ANTI_GROUND'] = 15
tower_ids['TOWER_ROCKET_ANTI_AIR'] = 16
