from constants import *

legacy_sound_data = {}
legacy_sound_data[UNIT_WORKER] = 				{ "move":["units_move_tank1"], "voorder":["ui_worker1", "ui_worker2", "ui_worker3", "ui_worker4"]};				
legacy_sound_data[UNIT_FOOT_RIFLE] = 			{ "move":[], "vocreate":["units_2_3.wav"], "voselect":["units_2_1.wav", "units_2_3.wav"], "voorder":["units_2_2.wav", "units_2_6.wav", "units_2_7.wav", "units_2_8.wav", "units_2_9.wav"], "voattack":["units_2_4.wav", "units_2_5.wav"] };
legacy_sound_data[UNIT_FOOT_SAW] = 				{ "move":[], "vocreate":["units_3_2.wav"], "voselect":["units_3_2.wav", "units_3_3.wav"], "voorder":["units_3_1.wav", "units_3_6.wav"], "voattack":["units_3_4.wav", "units_3_5.wav"] };
legacy_sound_data[UNIT_FOOT_RPG] = 				{ "move":[], "vocreate":["units_4_1.wav"], "voselect":["units_4_1.wav", "units_4_2.wav", "units_4_3.wav"], "voorder":["units_4_7.wav", "units_4_8.wav", "units_4_9.wav", "units_4_10.wav", "units_4_11.wav"], "voattack":["units_4_4.wav", "units_4_5.wav", "units_4_6.wav"] };
legacy_sound_data[UNIT_FOOT_FLAME] = 			{ "move":[], "vocreate":["units_5_4.wav"], "voselect":["units_5_4.wav", "units_5_5.wav", "units_5_7.wav"], "voorder":["units_5_2.wav", "units_5_6.wav"], "voattack":["units_5_1.wav", "units_5_3.wav"] };
legacy_sound_data[UNIT_FOOT_SNIPER] = 			{ "move":[], "vocreate":["units_6_5.wav"], "voselect":["units_6_1.wav", "units_6_5.wav"], "voorder":["units_6_6.wav", "units_6_7.wav", "units_6_8.wav", "units_6_9.wav", "units_6_10.wav", "units_6_11.wav", "units_6_12.wav"], "voattack":["units_6_2.wav", "units_6_3.wav", "units_6_4.wav"] };
legacy_sound_data[UNIT_FOOT_BOMBER] = 			{ "move":[], "vocreate":["units_7_5.wav"], "voselect":["units_7_5.wav", "units_7_6.wav"], "voorder":["units_7_3.wav", "units_7_4.wav"], "voattack":["units_7_2.wav"] };
legacy_sound_data[UNIT_FOOT_TECH] = 			{ "move":[], "vocreate":["units_8_1.wav"], "voselect":["units_8_1.wav", "units_8_6.wav"], "voorder":["units_8_2.wav", "units_8_5.wav"], "voattack":["units_8_3.wav", "units_8_4.wav"] };
legacy_sound_data[UNIT_FOOT_MEDIC] = 			{ "move":[], "vocreate":["units_9_1.wav"], "voselect":["units_9_1.wav", "units_9_4.wav", "units_9_5.wav"], "voorder":["units_9_7.wav", "units_9_8.wav", "units_9_9.wav", "units_9_10.wav", "units_9_11.wav"], "voattack":["units_9_2.wav", "units_9_3.wav", "units_9_6.wav"] };				
legacy_sound_data[UNIT_VEHICLE_TANKDRONE] =		{ "move":["units_move_tank1"], "vocreate":[], "voselect":["ui_drone_2"], "voorder":["ui_drone_2"], "voattack":["ui_drone_2"] };
legacy_sound_data[UNIT_VEHICLE_BUGGY] = 		{ "move":["units_move_buggy"], "vocreate":["units_11_8.wav"], "voselect":["units_11_2.wav", "units_11_7.wav", "units_11_8.wav"], "voorder":["units_11_3.wav", "units_11_4.wav", "units_11_9.wav", "units_11_10.wav", "units_11_11.wav", "units_11_12.wav", "units_11_13.wav"], "voattack":["units_11_5.wav", "units_11_6.wav"] };
legacy_sound_data[UNIT_VEHICLE_HUMVEE] = 		{ "move":["units_move_humvee"], "vocreate":["units_12_5.wav"], "voselect":["units_12_2.wav", "units_12_5.wav"], "voorder":["units_12_6.wav", "units_12_7.wav", "units_12_8.wav", "units_12_9.wav", "units_12_10.wav"], "voattack":["units_12_3.wav", "units_12_4.wav"] };
legacy_sound_data[UNIT_VEHICLE_MAV] = 			{ "move":["units_move_humvee"], "vocreate":["units_13_1.wav"], "voselect":["units_13_1.wav", "units_13_2.wav", "units_13_5.wav"], "voorder":["units_13_6.wav", "units_13_7.wav", "units_13_8.wav", "units_13_9.wav", "units_13_10.wav", "units_13_11.wav"], "voattack":["units_13_3.wav", "units_13_4.wav"] };
legacy_sound_data[UNIT_VEHICLE_TANK1] = 		{ "move":["units_move_tank1"], "vocreate":["units_14_1.wav"], "voselect":["units_14_1.wav", "units_14_2.wav"], "voorder":["units_14_4.wav", "units_14_5.wav", "units_14_6.wav", "units_14_7.wav", "units_14_8.wav"], "voattack":["units_14_3.wav"] };
legacy_sound_data[UNIT_VEHICLE_TANK2] = 		{ "move":["units_move_tank2"], "vocreate":["units_15_4.wav"], "voselect":["units_15_2.wav", "units_15_4.wav"], "voorder":["units_15_5.wav", "units_15_6.wav", "units_15_7.wav", "units_15_8.wav", "units_15_9.wav"], "voattack":["units_15_1.wav", "units_15_3.wav"] };
legacy_sound_data[UNIT_VEHICLE_TANK3] = 		{ "move":["units_move_tank3"], "vocreate":["units_16_5.wav"], "voselect":["units_16_1.wav", "units_16_5.wav", "units_16_6.wav"], "voorder":["units_16_7.wav", "units_16_8.wav", "units_16_9.wav", "units_16_10.wav", "units_16_11.wav"], "voattack":["units_16_2.wav", "units_16_3.wav", "units_16_4.wav"] };
legacy_sound_data[UNIT_VEHICLE_LASERTANK] = 	{ "move":["units_move_tank2"], "vocreate":["units_17_1.wav"], "voselect":["units_17_1.wav", "units_17_5.wav", "units_17_6.wav"], "voorder":["units_17_7.wav", "units_17_9.wav", "units_17_10.wav", "units_17_11.wav"], "voattack":["units_17_2.wav", "units_17_3.wav", "units_17_4.wav"] };
legacy_sound_data[UNIT_VEHICLE_ANTIAIR] = 		{ "move":["units_move_tank1"], "vocreate":["units_18_2.wav"], "voselect":["units_18_2.wav", "units_18_3.wav"], "voorder":["units_18_4.wav", "units_18_5.wav", "units_18_6.wav", "units_18_7.wav", "units_18_8.wav"], "voattack":["units_18_1.wav"] };
legacy_sound_data[UNIT_VEHICLE_JAMMER] = 		{ "move":["units_move_tank1"], "vocreate":["units_19_4.wav"], "voselect":["units_19_1.wav", "units_19_4.wav"], "voorder":["units_19_5.wav", "units_19_6.wav", "units_19_7.wav", "units_19_8.wav", "units_19_9.wav"], "voattack":["units_19_2.wav", "units_19_3.wav"] };
legacy_sound_data[UNIT_VEHICLE_ANTIMISSILE] =	{ "move":["units_move_tank1"], "vocreate":["units_20_1.wav"], "voselect":["units_20_1.wav", "units_20_2.wav"], "voorder":["units_20_4.wav", "units_20_5.wav", "units_20_6.wav", "units_20_7.wav", "units_20_8.wav"], "voattack":["units_20_3.wav"] };
legacy_sound_data[UNIT_VEHICLE_MEGATANK] = 		{ "move":["units_move_tank3"], "vocreate":["units_21_1.wav"], "voselect":["units_21_1.wav", "units_21_4.wav"], "voorder":["units_21_6.wav", "units_21_7.wav", "units_21_8.wav", "units_21_9.wav", "units_21_10.wav"], "voattack":["units_21_2.wav", "units_21_3.wav", "units_21_5.wav"] };
legacy_sound_data[UNIT_VEHICLE_RAILGUN] = 		{ "move":["units_move_tank3"] };
legacy_sound_data[UNIT_AIR_WINGDRONE] =			{ "move":[], "vocreate":[], "voselect":["ui_drone_2"], "voorder":["ui_drone_2"], "voattack":["ui_drone_2"] };
legacy_sound_data[UNIT_AIR_CHOPPERDRONE] =		{ "move":[], "vocreate":[], "voselect":["ui_drone_2"], "voorder":["ui_drone_2"], "voattack":["ui_drone_2"] };
legacy_sound_data[UNIT_AIR_CHOPPER1] =			{ "move":[], "vocreate":["units_24_4.wav"], "voselect":["units_24_1.wav", "units_24_4.wav"], "voorder":["units_24_5.wav", "units_24_6.wav", "units_24_7.wav", "units_24_8.wav", "units_24_9.wav"], "voattack":["units_24_2.wav", "units_24_3.wav"] };
legacy_sound_data[UNIT_AIR_CHOPPER2] =			{ "move":[], "vocreate":["units_25_1.wav"], "voselect":["units_25_1.wav", "units_25_4.wav"], "voorder":["units_25_5.wav", "units_25_6.wav", "units_25_7.wav", "units_25_8.wav", "units_25_9.wav"], "voattack":["units_25_2.wav", "units_25_3.wav"] };
legacy_sound_data[UNIT_AIR_PLANE1] =			{ "move":[], "vocreate":["units_26_6.wav"], "voselect":["units_26_1.wav", "units_26_5.wav", "units_26_6.wav"], "voorder":["units_26_7.wav", "units_26_8.wav", "units_26_9.wav", "units_26_10.wav", "units_26_11.wav"], "voattack":["units_26_3.wav", "units_26_4.wav"] };
legacy_sound_data[UNIT_AIR_PLANE2] =			{ "move":[], "vocreate":["units_27_2.wav"], "voselect":["units_27_2.wav", "units_27_5.wav", "units_27_6.wav"], "voorder":["units_27_7.wav", "units_27_8.wav", "units_27_9.wav", "units_27_10.wav", "units_27_11.wav"], "voattack":["units_27_3.wav", "units_27_4.wav"] };
legacy_sound_data[UNIT_FOOT_MECH] = 			{ "move":[], "vocreate":["units_28_1.wav"], "voselect":["units_28_1.wav", "units_28_2.wav"], "voorder":["units_28_3.wav"], "voattack":["units_28_4.wav", "units_28_5.wav"] };
legacy_sound_data[UNIT_VEHICLE_GAT] = 			{ "move":["units_move_humvee"], "vocreate":["units_12_5.wav"], "voselect":["units_12_2.wav", "units_12_5.wav"], "voorder":["units_12_6.wav", "units_12_7.wav", "units_12_8.wav", "units_12_9.wav", "units_12_10.wav"], "voattack":["units_12_3.wav", "units_12_4.wav"] };				
legacy_sound_data[UNIT_AIR_HAWK] =				{ "move":[], "vocreate":["units_25_1.wav"], "voselect":["units_25_1.wav", "units_25_4.wav"], "voorder":["units_25_5.wav", "units_25_6.wav", "units_25_7.wav", "units_25_8.wav", "units_25_9.wav"], "voattack":["units_25_2.wav", "units_25_3.wav"] };
legacy_sound_data[UNIT_FOOT_DOG] =         		{ "vocreate":["units_30_move.wav"], "voselect":["units_30_select.wav"], "voorder":["units_30_move.wav"], "voattack":["units_30_target.wav"], "melee":["units_30_attack.wav"], "die":["units_30_die.wav"], "dig":["units_30_dig.wav"] };
legacy_sound_data[UNIT_VEHICLE_TANKBUSTER] =	{ "move":["units_move_tank1"], "vocreate":[], "voselect":["ui_drone_2"], "voorder":["ui_drone_2"], "voattack":["ui_drone_2"] };legacy_sound_data[UNIT_VEHICLE_DEMO_TRUCK] = 	{ "move":[], "vocreate":["units_7_5.wav"], "voselect":["units_7_5.wav", "units_7_6.wav"], "voorder":["units_7_3.wav", "units_7_4.wav"], "voattack":["units_7_2.wav"] };
legacy_sound_data[UNIT_VEHICLE_FLAMEASSAULT] = 	{ "move":["units_move_humvee"] };				
